name:                hmatrix
version:             0.1.0.0
github:              "Vawlpe/hmatrix"
license:             GPL-3.0
author:              "Hazel (Vawlpe)"
maintainer:          "vawlpe@gmail.com"
copyright:           "2022 Hazel (Vawlpe)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Vawlpe/hmatrix#readme>

dependencies:
- base >= 4.7 && < 5
- random

library:
  source-dirs: src

executables:
  hmatrix-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmatrix

tests:
  hmatrix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmatrix
